spring:
  profiles:
    active: loadInitialData
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
mail:
  host: smtp.example.com
  port: 587
  username: your_email@example.com
  password: your_password
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true